### ISSUE TITLE
PR the various forks.

### ISSUE THREAD

**Issue by CmdrDats** [seancorfield/clj-soap#7]
Hi @seancorfield, @uswitch, @jpmonettas, @primedia, @andresvalenciano, @cpoile

This is more than a little bit ridiculous:

![screen shot 2015-01-22 at 12 12 53 pm](https://cloud.githubusercontent.com/assets/1006584/5853912/c8c7265e-a230-11e4-9ed0-9ec724c8dd8f.png)

Could I ask that everyone chip in with what their changes achieve and get them PR'd into a single project? (comment on this issue with the changes they've done and how it might impact/break API)

Preferably one of you can take the baton on this fairly low-key project, but I'm happy to be the one driving it needs be.

It would be really cool if we can get together on this and tighten this little library up. :)

Thanks!

**Comment by seancorfield** [comment]
The readme in my version makes it pretty clear that my fork is (and always has been) a dead end:

https://github.com/seancorfield/clj-soap/blob/master/README.md

As it says there, I've been looking for someone to take it over for about two years and no one has - despite several people showing interest. 

It never did what I wanted. I only modernized it so I could test it at work. I've done nothing on it since (apart from trying to make it really clear that I have no intention of maintaining it, since I don't use it!).
